# Generated by Django 2.0.5 on 2019-04-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ceated',
            new_name='created',
        ),
    ]
